### ISSUE TITLE
ERROR: Patching Failed unknown patch 

### ISSUE THREAD

**Issue by johnr283** [Ich73/GamePatcher#3]
I'm getting error "unknown patch" when trying to patch a cia file.

**Comment by Ich73** [comment]
When using GamePatcher, the patch file files come in a zip archive, and the error occurs when an individual patch file within the zip archive is not being recognized. I suspect that you are trying to use GamePatcher for a patch file that is not intended for use with GamePatcher, but instead designed to be patched manually. If you are sure that your patch is designed for use with GamePatcher, please send me the entire console output.

In theory, any patch can be used with GamePatcher if you zip all the individual xdelta patch files (e.g. the main patch file and the patch file for the banner) and either rename the patch files correctly or specify the required command line arguments so that GamePatcher knows which patch file is which (cf. [README.md](https://github.com/Ich73/GamePatcher?tab=readme-ov-file#using-game-patcher)).

**Comment by johnr283** [comment]
Here are the files I have:
Legend of Zelda, The - Majora's Mask 3D (USA) Decrypted.cia
Legend of Zelda, The - Majora's Mask 3D (v1.1.0) (USA).zip

Legend of Zelda, The - Tri Force Heroes (USA) Decrypted.cia
Legend of Zelda, The - Tri Force Heroes (v3.3.0) (USA).zip

If GamePatcher won't work, how can I patch them manually?

**Comment by Ich73** [comment]
To me, those filenames don't look like a translation or some sort of mod that you have to "patch" the game for. Could it be that you are simply trying to install the latest update for each game? If so, the update isn't "patched", you just need to find the update as a cia file and install it on your 3ds or citra like you would with the original game. In that case GamePatcher is not necessary. If my guess is wrong, can you tell me the contents of the zip files?

**Comment by johnr283** [comment]
Your right. I'm trying to update the cia files with the latest game updates. The zip files contain the updates, titled the same as the zip. It seems I'm going about it the wrong way. Is there a way that will work for me.

**Comment by Ich73** [comment]
Alright. Then neither GamePatcher nor manual patching is necessary. Just install the normal game (e.g. `Legend of Zelda, The - Majora's Mask 3D (USA) Decrypted.cia`) on your 3ds with FBI. Then unzip the update file (e.g. `Legend of Zelda, The - Majora's Mask 3D (v1.1.0) (USA).zip`) to get the CIA of the update (e.g. `Legend of Zelda, The - Majora's Mask 3D (v1.1.0) (USA).cia`) and install it on your 3ds via FBI as well. If you are using Citra, install the normal game (e.g. `Legend of Zelda, The - Majora's Mask 3D (USA) Decrypted.cia`) via `File > Install CIA...` and then also the CIA of the update (e.g. `Legend of Zelda, The - Majora's Mask 3D (v1.1.0) (USA).cia`).

**Comment by johnr283** [comment]
Got it. Thanks for your help.
